// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0GFf1OLQQvMpMgqMPNGbvzy7GoIDVV0',
    appId: '1:58436397984:web:f89d5ab9bcd9535c46d2c5',
    messagingSenderId: '58436397984',
    projectId: 'hikpro-46197',
    authDomain: 'hikpro-46197.firebaseapp.com',
    storageBucket: 'hikpro-46197.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbnlCTOv7P66JoKgbD0GgOzRLIIHV4iA',
    appId: '1:58436397984:android:1985a07340224d5546d2c5',
    messagingSenderId: '58436397984',
    projectId: 'hikpro-46197',
    storageBucket: 'hikpro-46197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHi0yc7wpYogSUR7RdVB_D42_uQ4GCBeM',
    appId: '1:58436397984:ios:417b12864d6d83ff46d2c5',
    messagingSenderId: '58436397984',
    projectId: 'hikpro-46197',
    storageBucket: 'hikpro-46197.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHi0yc7wpYogSUR7RdVB_D42_uQ4GCBeM',
    appId: '1:58436397984:ios:417b12864d6d83ff46d2c5',
    messagingSenderId: '58436397984',
    projectId: 'hikpro-46197',
    storageBucket: 'hikpro-46197.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG0GFf1OLQQvMpMgqMPNGbvzy7GoIDVV0',
    appId: '1:58436397984:web:2a4046ee087d977246d2c5',
    messagingSenderId: '58436397984',
    projectId: 'hikpro-46197',
    authDomain: 'hikpro-46197.firebaseapp.com',
    storageBucket: 'hikpro-46197.appspot.com',
  );

}