// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC14EA4L3D6XZs6zvxU75Sdx68ZcsF1eVY',
    appId: '1:329062677275:web:65a75038112ddc939371be',
    messagingSenderId: '329062677275',
    projectId: 'employee-19ecc',
    authDomain: 'employee-19ecc.firebaseapp.com',
    storageBucket: 'employee-19ecc.appspot.com',
    measurementId: 'G-1BMWLY91N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxyMemHtIJhRY0b_CQjTEyszE0HC7pglQ',
    appId: '1:329062677275:android:1838286968b3b73d9371be',
    messagingSenderId: '329062677275',
    projectId: 'employee-19ecc',
    storageBucket: 'employee-19ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XHBJjMV6Q2jcCxjFWnylQOQ_LIdj_kc',
    appId: '1:329062677275:ios:db9f32a3374610499371be',
    messagingSenderId: '329062677275',
    projectId: 'employee-19ecc',
    storageBucket: 'employee-19ecc.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XHBJjMV6Q2jcCxjFWnylQOQ_LIdj_kc',
    appId: '1:329062677275:ios:db9f32a3374610499371be',
    messagingSenderId: '329062677275',
    projectId: 'employee-19ecc',
    storageBucket: 'employee-19ecc.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC14EA4L3D6XZs6zvxU75Sdx68ZcsF1eVY',
    appId: '1:329062677275:web:8493a98b14e638da9371be',
    messagingSenderId: '329062677275',
    projectId: 'employee-19ecc',
    authDomain: 'employee-19ecc.firebaseapp.com',
    storageBucket: 'employee-19ecc.appspot.com',
    measurementId: 'G-TJ4MJQHB26',
  );

}