// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtktpT4mmoWytHUEGkmbauUZ-uSX9dBEE',
    appId: '1:335314328114:web:634cd6a5ca35c918103a2b',
    messagingSenderId: '335314328114',
    projectId: 'employee2-62c4d',
    authDomain: 'employee2-62c4d.firebaseapp.com',
    storageBucket: 'employee2-62c4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumc7YtO-3D7ONvYD-COrLhSQfjIAA9h0',
    appId: '1:335314328114:android:59ae0dd810aae8cc103a2b',
    messagingSenderId: '335314328114',
    projectId: 'employee2-62c4d',
    storageBucket: 'employee2-62c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFaUyi8oQPWoJwRLzL_JGoJ5X7oU0on0',
    appId: '1:335314328114:ios:ba75628533462b9f103a2b',
    messagingSenderId: '335314328114',
    projectId: 'employee2-62c4d',
    storageBucket: 'employee2-62c4d.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFaUyi8oQPWoJwRLzL_JGoJ5X7oU0on0',
    appId: '1:335314328114:ios:ba75628533462b9f103a2b',
    messagingSenderId: '335314328114',
    projectId: 'employee2-62c4d',
    storageBucket: 'employee2-62c4d.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtktpT4mmoWytHUEGkmbauUZ-uSX9dBEE',
    appId: '1:335314328114:web:27c740d6021897f2103a2b',
    messagingSenderId: '335314328114',
    projectId: 'employee2-62c4d',
    authDomain: 'employee2-62c4d.firebaseapp.com',
    storageBucket: 'employee2-62c4d.appspot.com',
  );

}